/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.compiladorchilero.views;

import com.compiladorchilero.controllers.AnalysisController;
import com.compiladorchilero.controllers.ArchiveReader;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MainFrame extends javax.swing.JFrame {

    private AnalysisController analysisController;
    private ArchiveReader archiveReader;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.errorTextArea.setEditable(false);
        this.resultTextArea.setEditable(false);
        this.analysisController = new AnalysisController();
        this.archiveReader = new ArchiveReader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        writingTextArea = new javax.swing.JTextArea();
        anaylzeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        errorTextArea = new javax.swing.JTextArea();
        cleanWritingTextArea = new javax.swing.JButton();
        cleanResultTextArea = new javax.swing.JButton();
        clearErrorLogTextArea = new javax.swing.JButton();
        uploadFileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        writingTextArea.setColumns(20);
        writingTextArea.setRows(5);
        jScrollPane1.setViewportView(writingTextArea);

        anaylzeButton.setText("Analizar Texto");
        anaylzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaylzeButtonActionPerformed(evt);
            }
        });

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        resultTextArea.setText("En este apartado podrás visualizar el resultado del código ingresado.");
        jScrollPane2.setViewportView(resultTextArea);

        errorTextArea.setColumns(20);
        errorTextArea.setRows(5);
        errorTextArea.setText("En este apartado podrás visualizar los errores que se obtengan durante el proceso de compilación y ejecución.");
        jScrollPane3.setViewportView(errorTextArea);

        cleanWritingTextArea.setText("Limpiar area de ingreso");
        cleanWritingTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanWritingTextAreaActionPerformed(evt);
            }
        });

        cleanResultTextArea.setText("Limpiar area de Resultado");
        cleanResultTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanResultTextAreaActionPerformed(evt);
            }
        });

        clearErrorLogTextArea.setText("Limpiar errores");
        clearErrorLogTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearErrorLogTextAreaActionPerformed(evt);
            }
        });

        uploadFileButton.setText("Cargar Archivo");
        uploadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Puedes escribir tu codigo debajo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(anaylzeButton)
                        .addGap(13, 13, 13)
                        .addComponent(uploadFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanWritingTextArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanResultTextArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearErrorLogTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cleanWritingTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anaylzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cleanResultTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearErrorLogTextArea)
                            .addComponent(uploadFileButton))
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anaylzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaylzeButtonActionPerformed
        if (this.writingTextArea.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "No puedes usar este boton si no hay texto que analizar");
        } else {
            this.analysisController.startAnalysis(this.writingTextArea, this.errorTextArea, this.resultTextArea, this);
        }
    }//GEN-LAST:event_anaylzeButtonActionPerformed

    private void cleanResultTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanResultTextAreaActionPerformed
        this.resultTextArea.setText("");
    }//GEN-LAST:event_cleanResultTextAreaActionPerformed

    private void cleanWritingTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanWritingTextAreaActionPerformed
        this.writingTextArea.setText("");
    }//GEN-LAST:event_cleanWritingTextAreaActionPerformed

    private void clearErrorLogTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearErrorLogTextAreaActionPerformed
        this.writingTextArea.setText("");
    }//GEN-LAST:event_clearErrorLogTextAreaActionPerformed

    private void uploadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileButtonActionPerformed
        JFileChooser fileChosser = new JFileChooser();
        int selection = fileChosser.showOpenDialog(this);
        this.writingTextArea.setText(" ");
        if (selection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChosser.getSelectedFile();
            try {
                this.archiveReader.readFile(selectedFile, this.writingTextArea);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo");
            }
        }
    }//GEN-LAST:event_uploadFileButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anaylzeButton;
    private javax.swing.JButton cleanResultTextArea;
    private javax.swing.JButton cleanWritingTextArea;
    private javax.swing.JButton clearErrorLogTextArea;
    private javax.swing.JTextArea errorTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton uploadFileButton;
    private javax.swing.JTextArea writingTextArea;
    // End of variables declaration//GEN-END:variables
}
